#+TITLE: Research Log 
#+AUTHOR: Victor Gan

* <2015-03-03 Tue>
** Ranking of CS Conferences
http://academic.research.microsoft.com/RankList?entitytype=3&topDomainID=2&subDomainID=0 
* <2015-02-28 Sat>

** iHaskell

* <2015-02-27 Fri> 
Julieta presented a really good paper in CVRG. Also, she referenced a
2010 paper from Malik that's also good.

** Stop GEdit from Making Backup Files
http://askubuntu.com/questions/83026/prevent-gedit-from-creating-files-with-the-tilde-suffix

** Make matlab terminal command
http://askubuntu.com/questions/185763/how-can-i-launch-matlab-2012

In short: make a symbolic link for the entire system and always run as root.

** Running fragkiadaki2014grouping

Following the readme, I extracted the files.

My idea: Do this but with RGB-D videos. 

** Thoughts on Video Object proposals

Quote:
"image segmentation", the partitioning of an image (or video stream)
into sets of pixels that correspond to "objects" or parts of
objects. This process is based on bottom up cues such as similarity of
pixel brightness, color, texture and motion as well as top down input
derived from familiar object categories such as faces.

I don't think this is the right way. Humans know things from motion
and depth. And if we can use motion and depth to get better object
proposals, we can automatically train a dataset, which can then be
used for other things.

Berkeley does segmentation:
http://http.cs.berkeley.edu/Research/Projects/CS/vision/grouping/

From the group:
Simultaneous detection and segmentation:
http://http.cs.berkeley.edu/Research/Projects/CS/vision/papers/BharathECCV2014.pdf

Learning Rich Features from RGB-D Images for Object Detection and Segmentation:
http://http.cs.berkeley.edu/Research/Projects/CS/vision/papers/SaurabhECCV2014.pdf

** RGB-D Optical Flow
https://homes.cs.washington.edu/~xren/publication/herbst-icra13-rgbd-flow.pdf

** TODO Idea: Interesting Event Detection
Optical flow + method to find non-linear dynamics in flow field =
interesting events

Images linear until edges of 

** TODO Idea: What colour do I call this?
Find out how people perceive colours.
Two light sources, iterate through white balances, see how the colour
of objects change in different lighting

** Random browsing about RGBD
RSS RGBD Workshop 2014: http://www.cs.cornell.edu/~hema/rgbd-workshop-2014/program.html
http://www.cs.cornell.edu/~hema/rgbd-workshop-2014/talks/NoahSnavely_RGBD2014.pdf

In http://www.cs.cornell.edu/~hema/rgbd-workshop-2014/talks/rgbd-robotics-fox.pdf:
There is a slide saying (p. 22) RGBD object recognition might not be researchy enough

** TODO Idea: Replace/initialize first layer of deep network with gabor filters

** Optical Flow, an Overview
Datasets: Middlebury, MPI Sintel, and KITTI datasets 

Original formulation: Horn and Schunck

Review paper: 
A quantitative analysis of current practices in optical flow estimation and the principles behind them
sun2014quantitative

I downloaded the code and it works!

Quotes:
We discover that classical flow formulations perform surprisingly well
when combined with modern optimization and implementation techniques


* <2015-02-26 Thu> 
  
** iHaskell and iPython.
I installed iPython.

* <2015-02-25 Wed>

** Video object proposals
I watched Geoff Hinton's talk at UBC
(https://www.youtube.com/watch?v=vShMxxqtDDs) where he mentions
identifying objects is insanely complicated to do by learning. I want
to do it, perhaps using video RGBD. 

Two potential papers:
http://www.umiacs.umd.edu/~mishraka/Files/segRGBD_ICRA_2012.pdf and
http://www.cs.berkeley.edu/~sgupta/pdf/rcnn-depth.pdf

I want to identify good objects in an unsupervised way, sort of like
object proposals but with almost perfect precision/recall. Object
detection without caring about what the object is. So far it's hard to
do that with plain images. It might be easier to do that with moving
objects.
*** TODO Idea: Perfect object-in-scene detection, without caring about labels.

*** Object Proposals
So Beneson and Piotr released a new object proposal benchmark. Sort of read it.
https://www.mpi-inf.mpg.de/departments/computer-vision-and-multimodal-computing/research/object-recognition-and-scene-understanding/how-good-are-detection-proposals-really/
With code: https://github.com/hosang/detection-proposals
I cloned it as detection-proposals.

** Nature: DNN for reinforcement learning
Google released a game-learning RL DNN: http://www.nature.com/nature/journal/v518/n7540/full/nature14236.html
Saved as mnih2015human.

I want to implement a basic reinforcement learning routine to understand it.
*** TODO Implement: Basic reinforcement learning routine
*** TODO Implement: Google's DNN RL

** Organize Ubuntu Computer's Dotfiles
I want to organize my dotfiles on the Ubuntu computer. Change my vim repository to a dotfiles repository.
Looking at https://dotfiles.github.io/:

Basic dotfile tutorial: https://medium.com/@webprolific/getting-started-with-dotfiles-43c3602fd789
Ahh. Is there no decent tutorial for this?!
This seems to be a decent one: https://github.com/webpro/dotfiles
Forked!

*** Bash command: source
source is a bash shell built-in command that executes the content of
the file passed as argument, in the current shell. It has a synonym in
'.' (period).
Syntax
      . filename [arguments]

      source filename [arguments]


Okay, modifying some more.
Yeah! I have emacs on ubuntu.
grimbergen seems to lock up sometimes. I don't know why.
Now to find out how to automatically commit.

Github on which URL I should use.
https://help.github.com/articles/which-remote-url-should-i-use/

So I want to not have to login all the time. To do that I set up an ssh key:
https://help.github.com/articles/generating-ssh-keys/

https://help.github.com/articles/changing-a-remote-s-url/

https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/#platform-linux

echo "# sun2014quantitative" >> README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin git@github.com:victorgan/sun2014quantitative.git
git push -u origin master

Testing. Okay maybe it works, maybe it doesn't.

** Downloading COCO
Tried. Didn't work because the computer froze.

** Installing Matlab
From the install file on my external hard drive.
Ran into this problem:
http://askubuntu.com/questions/184703/matlab-install-java-permission-denied

Full path of installation folder:
/usr/local/MATLAB/R2014a
Did not check "create symbolic links to matlab scripts in
/usr/local/bin" or any other folder


* <2015-02-23 Mon>
   I installed vimperator.
   Wow this is actually really great. 
   Okay, it saved. I lied.
